baseURL: "https://aldrichtr.github.io/"
languageCode: en-us
author: Tim Aldrich
enableInlineShortcodes: true

title: Tim Aldrich

build:
  writeStats: true

# Will give values to .Lastmod etc.
enableGitInfo: true


theme:
#  actually, it's my modified version of blonde...
#  - blonde
  - aldrichtr
