baseURL: "https://aldrichtr.github.io/"
author:
  name: Tim Aldrich
  email: timothy.r.aldrich@gmail.com

languageCode: en-us
copyright: "2022 Timothy Aldrich"

enableInlineShortcodes: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

title: Tim Aldrich

build:
  writeStats: true

# Will give values to .Lastmod etc.
enableGitInfo: true

theme: LoveIt

resources:
  - name: featured-image
    src: featured.png
  - name: featured-image-preview
    src: featured-preview.png
