baseURL: "https://aldrichtr.github.io/"
author:
  name: Tim Aldrich
  email: timothy.r.aldrich@gmail.com

languageCode: en-us
copyright: "2022 Timothy Aldrich"
enableInlineShortcodes: true

title: Tim Aldrich

build:
  writeStats: true

# Will give values to .Lastmod etc.
enableGitInfo: true

theme: LoveIt
