tableOfContents:
  startLevel: 2
  endLevel: 2
  ordered: true

highlight:
  anchorLineNos: false
  codeFences: true
  guessSyntax: false
  hl_Lines: ""
  lineAnchors: ""
  lineNoStart: 1
  lineNos: false
  lineNumbersInTable: true
  noClasses: true
  noHl: false
  style: native
  tabWidth: 4


defaultMarkdownHandler: goldmark

goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    linkifyProtocol: https
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    attribute:
      block: true
      title: true
    autoHeadingID: true
    autoHeadingIDType: github
  renderer:
    hardWraps: false
    unsafe: false
    xhtml: false
