main:
  - identifier: "posts"
    weight: 10
    pre: ''
    post: ''
    name: Blog
    url: "/posts/"
    title: "Posts"
  - identifier: "tags"
    weight: 20
    pre: ''
    post: ''
    name: Tags
    url: "/tags/"
    title: "Tags"
  - identifier: "categories"
    weight: 30
    pre: ''
    post: ''
    name: Categories
    url: "/categories/"
    title: "Categories"
  - identifier: About
    weight: 90
    pre: ''
    post: ''
    name: About
    url: "/about/"
    title: "AboutPages"
