favicon: "favicon.ico"

defaultTheme: "dark"

gitRepo: "https://github.com/aldrichtr/aldrichtr.github.io"

dateFormat: "2006 Jan 02"

header:
  desktopMode: "auto"
  mobileMode: "auto"
  title:
    logo: ""
    name: "Get-RandomIdea | Set-Content \"~/blog\""
    pre: ""
    post: ""
    typeit: false

footer:
  enable: true
  custom: ""
  hugo: true
  copyright: true
  author: true
  since: 2022
  license: "CC BY 4.0"

section:
  paginate: 25
  dateFormat: "Jan 02"
  rss: 10

list:
  paginate: 25
  dateFormat: "Jan 02"
  rss: 10

app:
  title: "Get-RandomIdea | Set-Content \"~/blog\""
# ---
social:
  github:
    id: aldrichtr
    weight: 0
  linkedin:
    id: timothy-r-aldrich
    weight: 1


search:
  enable: true
  type: "lunr"
  contentLength: 4000
  placeholder: ""
  maxResultLength: 10
  snippetLength: 30
  highlightTag: "em"
  absoluteURL: false
  algolia:
    index: ""
    appID: ""
    searchKey: ""

home:
  rss: 10
  profile:
    enable: true
    gravatarEmail: "timothy.r.aldrich@gmail.com"
    avatarURL: ""
    title: "Tim Aldrich"
    subtitle: "My personal blog"
    typeit: true
    social: true
    disclaimer: ""
  posts:
      enable: true
      paginate: 6

page:
  hiddenFromHomePage: false
  hiddenFromSearch: false
  twemoji: false
  lightgallery: false
  ruby: true
  fraction: true
  fontawesome: true
  linkToMarkdown: true
  rssFullText: false
  toc:
    enable: true
    keepStatic: false
    auto: true
  code:
    copy: true
    maxShownLines: 50
  math:
    enable: false
    inlineLeftDelimiter: ""
    inlineRightDelimiter: ""
    blockLeftDelimiter: ""
    blockRightDelimiter: ""
    copyTex: true
    mhchem: true
  mapbox:
    accessToken: ""
    lightStyle: "mapbox://styles/mapbox/light-v10?optimize=true"
    darkStyle: "mapbox://styles/mapbox/dark-v10?optimize=true"
    navigation: true
    geolocate: true
    scale: true
    fullscreen: true
  share:
    enable: true
    Twitter: true
    Facebook: true
    Linkedin: true
    Whatsapp: false
    Pinterest: false
    Tumblr: false
    HackerNews: true
    Reddit: false
    VK: false
    Buffer: false
    Xing: false
    Line: true
    Instapaper: false
    Pocket: false
    Flipboard: false
    Weibo: true
    Blogger: false
    Baidu: false
    Odnoklassniki: false
    Evernote: false
    Skype: false
    Trello: false
    Mix: false
    # Comment config
    # 评论系统设置
  comment:
    enable: false
    disqus:
      enable: false
    gitalk:
      enable: false
    valine:
      enable: false
    facebook:
      enable: false
    telegram:
      enable: false
    commento:
      enable: false
    utterances:
        enable: false
    giscus:
      enable: false

  library:
    css:
    js:
  seo:
   images: []
   publisher:
     name: ""
     logoUrl: ""

typeit:
  speed: 100
  cursorSpeed: 1000
  cursorChar: "|"
  duration: -1

verification:
  google: ""
  bing: ""
  yandex: ""
  pinterest: ""
  baidu: ""

seo:
  image: ""
  thumbnailUrl: ""

analytics:
  enable: false

cookieconsent:
  enable: false

cdn:
  data: "jsdelivr.yml"

  # Compatibility config
  # 兼容性设置
compatibility:
  polyfill: false
  objectFit: false
